name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit
        uses: wagoid/commitlint-github-action@v4
  
  test:
    needs: commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Eslint
        run: npm run lint
      